### ISSUE TITLE
weixin 小程序使用css3实现<del>样式

### ISSUE THREAD

**Issue by program-spiritual** [xiaomiwujiecao/geek-thickink#22]
```less
.del{
    text-decoration:underline;   //文字排版--下划线
    text-decoration:line-through;  //文字排版--删除线
}
```
